version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    container_name: wtest
    ports:
      - '8887:80'

  db:
    image: mysql
    container_name: dtest
    environment:
      MYSQL_ROOT_PASSWORD: Password123#@!
      MYSQL_DATABASE: cicd
      MYSQL_USER: root
      MYSQL_PASSWORD: Password123#@!

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: Password123#@!
      UPLOAD_LIMIT: 3000000000
    ports:
      - "8881:80"
    depends_on:
      - db