version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    container_name: webtest
    ports:
      - '8888:80'

  db:
    image: mysql
    container_name: dbtest
    environment:
      MYSQL_ROOT_PASSWORD: Password123#@!
      MYSQL_DATABASE: cicd
      MYSQL_USER: root
      MYSQL_PASSWORD: Password123#@!
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: Password123#@!
      UPLOAD_LIMIT: 3000000000
    ports:
      - "8881:80"
    depends_on:
      - db